### ISSUE TITLE
profanity text location

### ISSUE THREAD

**Issue by scheckley** [ruanrothmann/frogsmashers#3]
Hi,

Can you tell me the location of the text sprites that show when a user kills themselves? 

Thanks :)

**Comment by ruanrothmann** [comment]
EffectsController.cs line 437. At least I took out the f-bombs before uploading...

**Comment by scheckley** [comment]
cool, thanks for your help :)

**Comment by PNone** [comment]
@scheckley I suppose it may not be relevant, but I added a config file to my fork where you can change the death text options without the need to recompile. This version also comes with extra features, like 8 player local multiplayer, team deathmatch, a pause menu and match customization options :smile:

**Comment by scheckley** [comment]
> @scheckley I suppose it may not be relevant, but I added a config file to my fork where you can change the death text options without the need to recompile. This version also comes with extra features, like 8 player local multiplayer, team deathmatch, a pause menu and match customization options 😄

cool! have a star :)

**Comment by PNone** [comment]
> > @scheckley I suppose it may not be relevant, but I added a config file to my fork where you can change the death text options without the need to recompile. This version also comes with extra features, like 8 player local multiplayer, team deathmatch, a pause menu and match customization options 😄
> 
> cool! have a star :)

Thank you :)
